name = "mail-flare"
main = "worker/index.ts"
compatibility_date = "2026-04-02"

[assets]
directory = "./frontend/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "mailflare_db"
database_name = "mailflare-db"
database_id = "ecd12fe4-ea15-4679-8e86-3a3ef37f3080"
migrations_dir = "./migrations"
